# Task 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [13]:
def divide(a,b):
    
    try:
        output = a/b
        print("The division of {} and {} is {}".format(a, b,output))
    except ZeroDivisionError:
        print("Can't divide by zero")

divide(5,0)

Can't divide by zero


# Task 2. Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [15]:
subject=["Americans","Indians"]
verb=["play","watch"]
object=["Baseball","Cricket"]

for i in range(2):
    for j in range(2):
        for k in range(2):
            print(subject[i],verb[j],object[k])

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 3. Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde

In [22]:
import numpy as np
def mat(col,n):
    res=[]
    for j in col:
        w=[]
        for i in range(n):
            w.append(j**(n-i))
        res.append(w)
    return res
     
list=[2,3,4]
n2=4

print(np.array(mat(list,n2)))

[[ 16   8   4   2]
 [ 81  27   9   3]
 [256  64  16   4]]
